import { db } from "../db";
import { getSettings } from "../settings";
import { formatNaira } from "../money";
import { lagosDateStamp } from "../order-number";
import { evaluateRelease } from "../pricing/release";
import type { Block, DocModel } from "../pdf/render";

export type DocType = "INVOICE" | "QUOTATION" | "RECEIPT" | "PAYMENT_STATEMENT" | "INSTALLMENT_STATEMENT" | "RESERVATION" | "TRADE_IN" | "SWAP" | "BOOKING";

export const DOC_PREFIX: Record<DocType, string> = {
  INVOICE: "INV", QUOTATION: "QUO", RECEIPT: "RCT", PAYMENT_STATEMENT: "PST", INSTALLMENT_STATEMENT: "IST", RESERVATION: "RSV", TRADE_IN: "TRD", SWAP: "SWP", BOOKING: "BKG",
};
export const DOC_TITLE: Record<DocType, string> = {
  INVOICE: "TAX INVOICE", QUOTATION: "QUOTATION", RECEIPT: "PAYMENT RECEIPT", PAYMENT_STATEMENT: "PAYMENT STATEMENT", INSTALLMENT_STATEMENT: "INSTALLMENT STATEMENT",
  RESERVATION: "RESERVATION CONFIRMATION", TRADE_IN: "TRADE-IN VALUATION", SWAP: "CAR SWAP PROPOSAL", BOOKING: "SERVICE BOOKING CONFIRMATION",
};

export class DocumentError extends Error {}

const fmtDate = (d: Date) => new Intl.DateTimeFormat("en-NG", { timeZone: "Africa/Lagos", day: "2-digit", month: "long", year: "numeric" }).format(d);
const fmtDateTime = (d: Date) => new Intl.DateTimeFormat("en-NG", { timeZone: "Africa/Lagos", day: "2-digit", month: "short", year: "numeric", hour: "2-digit", minute: "2-digit", hour12: true }).format(d);
const money = (kobo: number | bigint) => formatNaira(Number(kobo), { whole: false });
const kobo = (v: bigint | number) => Number(v);

/** Sequential, collision-safe, stable number: the same subject always gets the same number. */
export async function getOrCreateDocument(type: DocType, refId: string, orderId?: string | null): Promise<{ number: string; createdAt: Date }> {
  const existing = await db.document.findUnique({ where: { type_refId: { type, refId } } });
  if (existing) return existing;
  try {
    return await db.$transaction(async (tx) => {
      const key = `${DOC_PREFIX[type]}-${lagosDateStamp()}`;
      const c = await tx.documentCounter.upsert({ where: { key }, create: { key, seq: 1 }, update: { seq: { increment: 1 } } });
      return tx.document.create({ data: { type, refId, orderId: orderId ?? null, number: `${key}-${String(c.seq).padStart(6, "0")}` } });
    });
  } catch (e) {
    // a concurrent request created it first (unique (type, refId)): return that one
    const again = await db.document.findUnique({ where: { type_refId: { type, refId } } });
    if (again) return again;
    throw e;
  }
}

async function seller() {
  const s = await getSettings();
  const lines = [
    String(s["legal.entityName"] || ""), s["legal.rcNumber"] ? `RC ${s["legal.rcNumber"]}` : "", s["legal.tin"] ? `TIN ${s["legal.tin"]}` : "",
    String(s["contact.address"] || ""), `${s["contact.phone1"]} · ${s["contact.phone2"]}`, String(s["contact.email"] || ""),
  ].filter(Boolean);
  const base = process.env.APPLICATION_URL ?? "";
  return {
    name: String(s["brand.name"]), lines, tagline: String(s["brand.tagline"]),
    footer: `${s["brand.name"]}. All amounts are in Nigerian Naira (NGN). This document is generated by our system${base ? ` and can be verified at ${base}` : ""}. Subject to our Terms and Conditions.`,
  };
}

async function activeBanks() {
  return db.bankAccount.findMany({ where: { isActive: true }, orderBy: { sortOrder: "asc" } });
}

const customerMeta = (c: { name: string; email: string | null; phone: string | null; address?: string | null; city?: string | null; state?: string | null }): [string, string][] => [
  ["Customer", c.name], ["Email", c.email ?? "-"], ["Phone", c.phone ?? "-"], ...(c.address || c.city ? ([["Address", [c.address, c.city, c.state].filter(Boolean).join(", ")]] as [string, string][]) : []),
];

async function loadOrder(orderId: string) {
  return db.order.findUniqueOrThrow({
    where: { id: orderId },
    include: { customer: true, items: { include: { product: { include: { vehicle: true } } } }, payments: { orderBy: { createdAt: "asc" } }, installment: true, reservations: true },
  });
}
type LoadedOrder = Awaited<ReturnType<typeof loadOrder>>;

function itemRows(o: LoadedOrder): string[][] {
  return o.items.map((i) => {
    const v = i.product.vehicle;
    const desc = [i.name, `SKU ${i.sku}`, v ? [v.stockNumber && `Stock ${v.stockNumber}`, v.vin && `VIN ${v.vin}`].filter(Boolean).join(" · ") : ""].filter(Boolean).join("\n");
    return [desc, String(i.quantity), money(i.unitPrice), money(i.discount), money(i.vat), money(i.lineTotal)];
  });
}
const itemColumns = [
  { header: "Description", width: 38 }, { header: "Qty", width: 6, align: "right" as const }, { header: "Unit price", width: 15, align: "right" as const },
  { header: "Discount", width: 13, align: "right" as const }, { header: "VAT", width: 13, align: "right" as const }, { header: "Amount", width: 15, align: "right" as const },
];

function totalsRows(o: LoadedOrder, withPaid: boolean) {
  const paid = kobo(o.amountPaid), payable = Math.max(0, kobo(o.grandTotal) - kobo(o.tradeInCredit));
  const rows: { label: string; value: string; strong?: boolean }[] = [{ label: "Subtotal", value: money(o.subtotal) }];
  if (kobo(o.discountTotal) > 0) rows.push({ label: "Discount", value: `-${money(o.discountTotal)}` });
  if (kobo(o.upliftTotal) > 0) rows.push({ label: "FAGDAN installment adjustment", value: money(o.upliftTotal) });
  if (kobo(o.chargesTotal) > 0) rows.push({ label: "Delivery and other charges", value: money(o.chargesTotal) });
  rows.push({ label: o.vatEnabled ? `VAT (${o.vatRateBps / 100}%)` : "VAT (exempt)", value: money(o.vatTotal) });
  rows.push({ label: "Total", value: money(o.grandTotal), strong: true });
  if (kobo(o.tradeInCredit) > 0) rows.push({ label: "Trade-in credit", value: `-${money(o.tradeInCredit)}` });
  if (withPaid) { rows.push({ label: "Paid (verified)", value: money(paid) }); rows.push({ label: "Balance due", value: money(Math.max(0, payable - paid)), strong: true }); }
  return rows;
}

function bankBlocks(banks: Awaited<ReturnType<typeof activeBanks>>, reference: string): Block[] {
  if (banks.length === 0) return [];
  const out: Block[] = [{ kind: "heading", text: "How to pay" }];
  out.push({ kind: "table", columns: [{ header: "Bank", width: 22 }, { header: "Account name", width: 38 }, { header: "Account number", width: 22 }, { header: "Type", width: 18 }], rows: banks.map((b) => [b.bankName, b.accountName, b.accountNumber, b.accountType]) });
  out.push({ kind: "paragraph", text: `Use ${reference} as your payment narration, then upload your proof of payment on your order page. Online payment by card, transfer or USSD is also available through Paystack when enabled.`, small: true });
  return out;
}

async function base(type: DocType, refId: string, orderId?: string | null) {
  const [doc, sel] = await Promise.all([getOrCreateDocument(type, refId, orderId), seller()]);
  return { doc, sel, model: (blocks: Block[]): DocModel => ({ title: DOC_TITLE[type], number: doc.number, date: fmtDate(doc.createdAt), seller: { name: sel.name, lines: sel.lines }, footerNote: sel.footer, blocks }) };
}

export async function buildInvoice(orderId: string, kind: "INVOICE" | "QUOTATION" = "INVOICE"): Promise<DocModel> {
  const o = await loadOrder(orderId);
  const { model } = await base(kind, o.id, o.id);
  const banks = await activeBanks();
  const paid = kobo(o.amountPaid), payable = Math.max(0, kobo(o.grandTotal) - kobo(o.tradeInCredit));
  const blocks: Block[] = [
    { kind: "meta", left: [...customerMeta(o.customer), ...(o.deliveryAddress ? ([["Deliver to", [o.deliveryAddress, o.deliveryCity, o.deliveryState].filter(Boolean).join(", ")]] as [string, string][]) : [])], right: [["Order number", o.orderNumber], ["Order date", fmtDate(o.createdAt)], ["Payment type", o.paymentMode === "INSTALLMENT" ? "FAGDAN installment" : "Outright"], ...(kind === "QUOTATION" ? ([["Valid until", fmtDate(new Date(+o.createdAt + 7 * 86_400_000))]] as [string, string][]) : [])] },
    { kind: "spacer", height: 4 }, { kind: "heading", text: "Items" },
    { kind: "table", columns: itemColumns, rows: itemRows(o) },
    { kind: "totals", rows: totalsRows(o, kind === "INVOICE") },
  ];
  if (o.vatExemptionStatus) blocks.push({ kind: "paragraph", text: `VAT exemption status: ${o.vatExemptionStatus.replace(/_/g, " ").toLowerCase()}.`, small: true });
  if (o.paymentMode === "INSTALLMENT") blocks.push({ kind: "banner", tone: "info", text: `Installment order: the vehicle is released once at least ${money(o.releaseThreshold)} has been paid and verified.` });
  if (kind === "INVOICE" && payable - paid <= 0 && payable > 0) blocks.push({ kind: "banner", tone: "ok", text: "PAID IN FULL. Thank you." });
  if (kind === "QUOTATION") blocks.push({ kind: "paragraph", text: "This quotation is not a tax invoice. Prices and availability are confirmed when your order is paid. Vehicles are held only while a valid reservation is active.", small: true });
  if (payable - paid > 0) blocks.push(...bankBlocks(banks, o.orderNumber));
  return model(blocks);
}

export async function buildReceipt(paymentId: string): Promise<DocModel> {
  const p = await db.payment.findUniqueOrThrow({ where: { id: paymentId }, include: { order: { include: { customer: true } } } });
  if (p.status !== "SUCCESS") throw new DocumentError("A receipt is only available for verified payments.");
  const { model } = await base("RECEIPT", p.id, p.orderId);
  const upTo = await db.ledgerEntry.aggregate({ where: { orderId: p.orderId, createdAt: { lte: (await db.ledgerEntry.findFirst({ where: { paymentId: p.id } }))?.createdAt ?? new Date() } }, _sum: { amount: true } });
  const o = p.order;
  const payable = Math.max(0, kobo(o.grandTotal) - kobo(o.tradeInCredit));
  const paidSoFar = kobo(upTo._sum.amount ?? 0n);
  return model([
    { kind: "meta", left: customerMeta(o.customer), right: [["Order number", o.orderNumber], ["Payment reference", p.reference], ["Method", p.method === "PAYSTACK" ? `Paystack${p.channel ? ` (${p.channel})` : ""}` : "Bank transfer"], ["Date verified", p.verifiedAt ? fmtDateTime(p.verifiedAt) : fmtDateTime(p.updatedAt)]] },
    { kind: "banner", tone: "ok", text: `RECEIVED WITH THANKS: ${money(p.paidAmount)}` },
    { kind: "heading", text: "Allocation" },
    { kind: "totals", rows: [{ label: "Order total", value: money(o.grandTotal) }, ...(kobo(o.tradeInCredit) > 0 ? [{ label: "Trade-in credit", value: `-${money(o.tradeInCredit)}` }] : []), { label: "This payment", value: money(p.paidAmount) }, { label: "Total paid to date", value: money(paidSoFar) }, { label: "Balance remaining", value: money(Math.max(0, payable - paidSoFar)), strong: true }] },
    { kind: "paragraph", text: "This receipt confirms money received and verified by FAGDAN. It is not a tax invoice; your invoice is available from your order page.", small: true },
  ]);
}

export async function buildPaymentStatement(orderId: string): Promise<DocModel> {
  const o = await loadOrder(orderId);
  const { model } = await base("PAYMENT_STATEMENT", o.id, o.id);
  const payable = Math.max(0, kobo(o.grandTotal) - kobo(o.tradeInCredit)), paid = kobo(o.amountPaid);
  return model([
    { kind: "meta", left: customerMeta(o.customer), right: [["Order number", o.orderNumber], ["Statement date", fmtDate(new Date())], ["Order status", o.status.replace(/_/g, " ")]] },
    { kind: "heading", text: "Payments" },
    { kind: "table", columns: [{ header: "Date", width: 20 }, { header: "Reference", width: 30 }, { header: "Method", width: 16 }, { header: "Status", width: 18 }, { header: "Amount", width: 16, align: "right" }], emptyText: "No payments recorded yet.", rows: o.payments.map((p) => [fmtDate(p.createdAt), p.reference, p.method === "PAYSTACK" ? "Paystack" : "Bank transfer", p.status.replace(/_/g, " ").toLowerCase(), money(p.status === "SUCCESS" ? p.paidAmount : p.expectedAmount)]) },
    { kind: "totals", rows: [{ label: "Order total", value: money(o.grandTotal) }, ...(kobo(o.tradeInCredit) > 0 ? [{ label: "Trade-in credit", value: `-${money(o.tradeInCredit)}` }] : []), { label: "Verified payments", value: money(paid) }, { label: "Balance due", value: money(Math.max(0, payable - paid)), strong: true }] },
    { kind: "paragraph", text: "Only payments with status 'success' (verified) count toward your balance. Pending or rejected payments are listed for information.", small: true },
  ]);
}

export async function buildInstallmentStatement(orderId: string): Promise<DocModel> {
  const o = await loadOrder(orderId);
  if (o.paymentMode !== "INSTALLMENT" || !o.installment) throw new DocumentError("This order is not on FAGDAN installment terms.");
  const { model } = await base("INSTALLMENT_STATEMENT", o.id, o.id);
  const plan = o.installment, paid = kobo(o.amountPaid), payable = Math.max(0, kobo(o.grandTotal) - kobo(o.tradeInCredit));
  const rel = evaluateRelease(paid, kobo(o.releaseThreshold));
  const verified = o.payments.filter((p) => p.status === "SUCCESS");
  return model([
    { kind: "meta", left: customerMeta(o.customer), right: [["Order number", o.orderNumber], ["Statement date", fmtDate(new Date())], ["Vehicle", o.items.map((i) => i.name).join(", ")]] },
    { kind: "heading", text: "Your installment plan" },
    { kind: "totals", rows: [{ label: "Outright price", value: money(plan.outrightPrice) }, { label: `FAGDAN installment price (+${plan.upliftBps / 100}%)`, value: money(plan.installmentPrice) }, { label: `VAT (${o.vatRateBps / 100}%)`, value: money(o.vatTotal) }, { label: "Installment total", value: money(o.grandTotal), strong: true }, { label: "Deposit agreed", value: money(plan.deposit) }, { label: `Release threshold (${plan.thresholdBps / 100}%)`, value: money(o.releaseThreshold) }] },
    { kind: "heading", text: "Verified payments" },
    { kind: "table", columns: [{ header: "Date", width: 24 }, { header: "Reference", width: 40 }, { header: "Method", width: 18 }, { header: "Amount", width: 18, align: "right" }], emptyText: "No verified payments yet.", rows: verified.map((p) => [fmtDate(p.verifiedAt ?? p.createdAt), p.reference, p.method === "PAYSTACK" ? "Paystack" : "Bank transfer", money(p.paidAmount)]) },
    { kind: "totals", rows: [{ label: "Total paid and verified", value: money(paid) }, { label: "Balance due", value: money(Math.max(0, payable - paid)), strong: true }, { label: "Needed to reach release threshold", value: money(rel.shortfall) }] },
    rel.state === "ELIGIBLE" ? { kind: "banner", tone: "ok", text: "RELEASE ELIGIBLE: the payment threshold has been met. Our team will contact you to arrange collection or delivery." } : { kind: "banner", tone: "danger", text: `RELEASE BLOCKED: ${money(rel.shortfall)} more must be paid and verified before the vehicle can be released.` },
    { kind: "paragraph", text: "FAGDAN installment is a commercial payment arrangement with FAGDAN, not a bank loan. See the FAGDAN Installment Terms on our website for default, cancellation and refund provisions.", small: true },
  ]);
}

export async function buildReservation(orderId: string): Promise<DocModel> {
  const o = await loadOrder(orderId);
  const vehicleItems = o.items.filter((i) => i.product.type === "VEHICLE");
  if (vehicleItems.length === 0) throw new DocumentError("This order has no vehicle to reserve.");
  const { model } = await base("RESERVATION", o.id, o.id);
  const r = o.reservations[0];
  const v = vehicleItems[0].product.vehicle;
  const status = r ? r.status : "NONE";
  return model([
    { kind: "meta", left: customerMeta(o.customer), right: [["Order number", o.orderNumber], ["Reserved on", fmtDate(r?.createdAt ?? o.createdAt)], ["Hold status", status === "ACTIVE" ? `Held until ${fmtDateTime(r!.expiresAt)}` : status === "CONVERTED" ? "Confirmed (payment received)" : status === "EXPIRED" ? "Expired" : status === "CANCELLED" ? "Cancelled" : "n/a"]] },
    { kind: "heading", text: "Reserved vehicle" },
    { kind: "table", columns: [{ header: "Vehicle", width: 36 }, { header: "Stock no.", width: 20 }, { header: "VIN", width: 28 }, { header: "Price", width: 16, align: "right" }], rows: vehicleItems.map((i) => [i.name, i.product.vehicle?.stockNumber ?? "-", i.product.vehicle?.vin ?? "-", money(i.unitPrice)]) },
    { kind: "meta", left: [["Inventory ID", v?.inventoryId ?? "-"], ["Deposit paid", money(r?.deposit ?? 0)], ["Order total", money(o.grandTotal)], ["Amount verified", money(o.amountPaid)]] },
    { kind: "banner", tone: status === "ACTIVE" ? "warn" : status === "CONVERTED" ? "ok" : "danger", text: status === "ACTIVE" ? "Your reservation is held for a limited time. It lapses automatically if payment is not verified before the hold expires." : status === "CONVERTED" ? "Your reservation is confirmed. The vehicle will not be offered to anyone else." : "This reservation is no longer active." },
    { kind: "paragraph", text: "A reservation holds one specific vehicle for you; it is not a transfer of ownership. Release of the vehicle follows the payment rules in your order and our Terms and Conditions.", small: true },
  ]);
}

export async function buildTradeIn(id: string): Promise<DocModel> {
  const t = await db.tradeIn.findUniqueOrThrow({ where: { id }, include: { customer: true } });
  const { model } = await base("TRADE_IN", t.id);
  return model([
    { kind: "meta", left: customerMeta(t.customer), right: [["Reference", t.id.slice(-10).toUpperCase()], ["Submitted", fmtDate(t.createdAt)], ["Status", t.status.replace(/_/g, " ")]] },
    { kind: "heading", text: "Your vehicle" },
    { kind: "meta", left: [["Vehicle", `${t.year} ${t.make} ${t.model}`], ["Mileage", t.mileageKm != null ? `${t.mileageKm.toLocaleString("en-NG")} km` : "-"], ["Condition (declared)", t.condition ?? "-"]] },
    { kind: "heading", text: "Valuation" },
    t.valuation ? { kind: "banner", tone: "info", text: `Indicative trade-in value: ${money(t.valuation)}${t.valuationExpiresAt ? `. Valid until ${fmtDate(t.valuationExpiresAt)}` : ""}` } : { kind: "banner", tone: "warn", text: "Valuation pending. Our appraiser will contact you." },
    { kind: "paragraph", text: "This valuation is indicative and subject to physical inspection, verification of ownership documents (registration, customs and proof of ownership) and the condition declared. When applied to a purchase, the amount is shown on your invoice as a trade-in credit.", small: true },
  ]);
}

export async function buildSwap(id: string): Promise<DocModel> {
  const s = await db.swapRequest.findUniqueOrThrow({ where: { id }, include: { customer: true } });
  const target = s.targetProductId ? await db.product.findUnique({ where: { id: s.targetProductId } }) : null;
  const { model } = await base("SWAP", s.id);
  const diff = s.cashDifference != null ? kobo(s.cashDifference) : null;
  return model([
    { kind: "meta", left: customerMeta(s.customer), right: [["Reference", s.id.slice(-10).toUpperCase()], ["Requested", fmtDate(s.createdAt)], ["Status", s.status.replace(/_/g, " ")]] },
    { kind: "heading", text: "Swap details" },
    { kind: "meta", left: [["Your vehicle", s.ownVehicle], ["Value of your vehicle", s.customerVehicleValue != null ? money(s.customerVehicleValue) : "Pending valuation"], ["Requested vehicle", target?.name ?? "To be agreed"], ["Value of requested vehicle", s.targetValue != null ? money(s.targetValue) : target ? money(target.price) : "Pending"]] },
    diff == null ? { kind: "banner", tone: "warn", text: "Cash difference to be confirmed after valuation." } : { kind: "banner", tone: "info", text: diff >= 0 ? `Cash difference payable by you: ${money(diff)}` : `Cash difference payable to you: ${money(-diff)}` },
    { kind: "paragraph", text: "This is a proposal for discussion, not a binding agreement. A swap is completed only after both vehicles are inspected, ownership documents are verified, and a written agreement is signed by both parties.", small: true },
  ]);
}

export async function buildBooking(id: string): Promise<DocModel> {
  const b = await db.serviceBooking.findUniqueOrThrow({ where: { id }, include: { service: true, customer: true } });
  const { model } = await base("BOOKING", b.id);
  return model([
    { kind: "meta", left: customerMeta(b.customer), right: [["Booking reference", b.id.slice(-10).toUpperCase()], ["Status", b.status.replace(/_/g, " ")], ["Booked on", fmtDate(b.createdAt)]] },
    { kind: "heading", text: "Appointment" },
    { kind: "meta", left: [["Service", b.service.name], ["Date and time", fmtDateTime(b.slotStart)], ["Expected duration", `${b.service.durationMin} minutes`], ["Location", b.location], ["Vehicle", b.vehicleInfo], ["Notes", b.notes ?? "-"], ["Estimated price", `From ${money(b.service.price)} (plus VAT where applicable)`]] },
    { kind: "banner", tone: "info", text: "Please arrive 10 minutes early and bring your vehicle documents. We confirm any extra cost before starting work." },
    { kind: "paragraph", text: "To change or cancel, contact us as early as possible so that the slot can be offered to someone else.", small: true },
  ]);
}
