import { Prisma, type ProductType } from "@prisma/client";
import { db } from "./db";

const PREFIX: Record<ProductType, string> = { VEHICLE: "VEH", PART: "PRT", ACCESSORY: "ACC", TECHNOLOGY: "TEC", SERVICE: "SVC", OTHER: "OTH" };

type Client = Prisma.TransactionClient | typeof db;

async function next(client: Client, key: string): Promise<number> {
  const c = await client.documentCounter.upsert({ where: { key }, create: { key, seq: 1 }, update: { seq: { increment: 1 } } });
  return c.seq;
}

/** Collision-safe, sequential identifiers generated by the system (the admin may still override them). */
export async function generateSku(type: ProductType, client: Client = db): Promise<string> {
  for (let attempt = 0; attempt < 20; attempt++) {
    const sku = `${PREFIX[type]}-${String(await next(client, `SKU-${PREFIX[type]}`)).padStart(6, "0")}`;
    if (!(await client.product.findUnique({ where: { sku }, select: { id: true } }))) return sku;
  }
  throw new Error("Could not generate a unique SKU");
}

export async function generateInventoryId(client: Client = db): Promise<string> {
  for (let attempt = 0; attempt < 20; attempt++) {
    const id = `FAG-INV-${String(await next(client, "ID-INV")).padStart(6, "0")}`;
    if (!(await client.vehicle.findUnique({ where: { inventoryId: id }, select: { productId: true } }))) return id;
  }
  throw new Error("Could not generate a unique inventory ID");
}

export async function generateStockNumber(year: number, client: Client = db): Promise<string> {
  for (let attempt = 0; attempt < 20; attempt++) {
    const n = `STK-${year}-${String(await next(client, `ID-STK-${year}`)).padStart(4, "0")}`;
    if (!(await client.vehicle.findUnique({ where: { stockNumber: n }, select: { productId: true } }))) return n;
  }
  throw new Error("Could not generate a unique stock number");
}
